#!/bin/bash

set -euf -o pipefail

smtp_hostname="localhost"
smtp_port="25"
smtp_username=""
smtp_password=""

database_username="$USER"
database_password="$USER"

source "local/project-config"
source "config/env-config"

cat > "config/build.properties" <<-END
	database.name = ${database_name}
END

cat > "config/wbs-config.xml" <<-END
	<wbs-config
	  name="${project_title} dev local"
	  home-directory="$(pwd)"
	  console-title="${project_title} dev local"
	  api-url="${public_url}/api"
	  http-user-agent="${project_title} dev local"
	  default-slice="${default_slice}"
	  default-timezone="${default_timezone}"
	  cryptor-seed="${cryptor_seed}">

	  <database
	    hostname="localhost"
	    username="${database_username}"
	    password="${database_password}"
	    database-name="${database_name}"/>

	  <email
	    smtp-hostname="${smtp_username}"
	    smtp-port="${smtp_port}"
	    smtp-username="${smtp_username}"
	    smtp-password="${smtp_password}"
	    default-envelope-from="${developer_email}"
	    default-from-name="${project_title} dev local"
	    default-from-address="${platform_email}"
	    default-reply-to-address="${developer_email}"
	    developer-address="${developer_email}"/>

	  <process-api
	    listen-port="${port_base}082"/>

	  <console-server
	    listen-port="${port_base}083"/>

	</wbs-config>
END

cat > "config/wbs-api-config.xml" <<-END
	<wbs-config
	  name="${project_title} dev local"
	  home-directory="$(pwd)"
	  console-title="${project_title} dev local"
	  api-url="${public_url}/api"
	  http-user-agent="${project_title} dev local"
	  default-slice="${default_slice}"
	  default-timezone="${default_timezone}"
	  cryptor-seed="${cryptor_seed}">

	  <database
	    hostname="localhost"
	    username="${database_username}"
	    password="${database_password}"
	    database-name="${database_name}"/>

	  <email
	    smtp-hostname="${smtp_username}"
	    smtp-port="${smtp_port}"
	    smtp-username="${smtp_username}"
	    smtp-password="${smtp_password}"
	    default-envelope-from="${developer_email}"
	    default-from-name="${project_title} dev local"
	    default-from-address="${platform_email}"
	    default-reply-to-address="${developer_email}"
	    developer-address="${developer_email}"/>

	  <process-api
	    listen-port="${port_base}182"/>

	  <console-server
	    listen-port="${port_base}183"/>

	</wbs-config>
END

cat > "config/wbs-daemon-config.xml" <<-END
	<wbs-config
	  name="${project_title} dev local"
	  home-directory="$(pwd)"
	  console-title="${project_title} dev local"
	  api-url="${public_url}/api"
	  http-user-agent="${project_title} dev local"
	  default-slice="${default_slice}"
	  default-timezone="${default_timezone}"
	  cryptor-seed="${cryptor_seed}">

	  <database
	    hostname="localhost"
	    username="${database_username}"
	    password="${database_password}"
	    database-name="${database_name}"/>

	  <email
	    smtp-hostname="${smtp_username}"
	    smtp-port="${smtp_port}"
	    smtp-username="${smtp_username}"
	    smtp-password="${smtp_password}"
	    default-envelope-from="${developer_email}"
	    default-from-name="${project_title} dev local"
	    default-from-address="${platform_email}"
	    default-reply-to-address="${developer_email}"
	    developer-address="${developer_email}"/>

	  <process-api
	    listen-port="${port_base}282"/>

	  <console-server
	    listen-port="${port_base}283"/>

	</wbs-config>
END

cat > "config/wbs-console-config.xml" <<-END
	<wbs-config
	  name="${project_title} dev local"
	  home-directory="$(pwd)"
	  console-title="${project_title} dev local"
	  api-url="${public_url}/api"
	  http-user-agent="${project_title} dev local"
	  default-slice="${default_slice}"
	  default-timezone="${default_timezone}"
	  cryptor-seed="${cryptor_seed}">

	  <database
	    hostname="localhost"
	    username="${database_username}"
	    password="${database_password}"
	    database-name="${database_name}"/>

	  <email
	    smtp-hostname="${smtp_username}"
	    smtp-port="${smtp_port}"
	    smtp-username="${smtp_username}"
	    smtp-password="${smtp_password}"
	    default-envelope-from="${developer_email}"
	    default-from-name="${project_title} dev local"
	    default-from-address="${platform_email}"
	    default-reply-to-address="${developer_email}"
	    developer-address="${developer_email}"/>

	  <test-users>
	    <test-user name="$test_user_0"/>
	    <test-user name="$test_user_1"/>
	    <test-user name="$test_user_2"/>
	    <test-user name="$test_user_3"/>
	  </test-users>

	  <process-api
	    listen-port="${port_base}082"/>

	  <console-server
	    listen-port="${port_base}083"/>

	</wbs-config>
END

cat > "config/tomcat-users.xml" <<-END
	<?xml version='1.0' encoding='utf-8'?>
	<tomcat-users>
	  <role rolename="tomcat"/>
	  <role rolename="role1"/>
	  <user username="tomcat" password="tomcat" roles="tomcat"/>
	  <user username="both" password="tomcat" roles="tomcat,role1"/>
	  <user username="role1" password="tomcat" roles="role1"/>
	</tomcat-users>
END

# ex: noet ts=4 filetype=bash
